modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "vr_iron_man"
version = "${version}"
displayName = "VR IRON MAN"
authors = "mafuyu33"
description = '''
VR IRON MAN MOD DEPEND ON VR PLAYGROUND
'''
#logoFile = ""

[[dependencies.vr_iron_man]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vr_iron_man]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vr_iron_man]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"